name: Frontend 프로덕션 서버 EC2 배포

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 배포 작업
    runs-on: ubuntu-latest

    env:
      CONTAINER_NAME: sulmun2yong_frontend_prod
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v2

    - name: EC2에 배포
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.FRONTEND_EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.PRODUCTION_EC2_KEY }}
        script: |
          # 스크립트 실패 시 workflow도 실패하도록 설정
          set -e
          cd ~/Frontend
          git pull origin main
          echo "${{ secrets.FRONTEND_PROD_ENV_CONTENT }}" > .env.local
          docker stop ${{ env.CONTAINER_NAME }} || true
          docker rm ${{ env.CONTAINER_NAME }} || true
          docker build -t ${{ env.CONTAINER_NAME }}:latest . 
          docker run -d -p 3000:3000 --name ${{ env.CONTAINER_NAME }} ${{ env.CONTAINER_NAME }}:latest
          docker image prune -af
